### ISSUE TITLE
Unity2021.3.18 反序列化报错

### ISSUE THREAD

**Issue by Justin-sky** [crossous/SocoTools#2]
AssetDatabase.LoadAssetAtPath<ShaderVariantsStripperConfig>(
                AssetDatabase.GUIDToAssetPath(guid));   在反序列化ShaderConditionsDictionary 结构时报错

**Comment by Justin-sky** [comment]
![image](https://user-images.githubusercontent.com/58215826/228111590-840800d2-87d0-4804-8892-0c806cfb67ed.png)

**Comment by crossous** [comment]
报错是在ShaderVariantsStripperCode.LoadConfigs方法内部吗
我用2021.3.5测试没有报错，能否更详细的信息，例如：
这个工具的代码是否变更过程序集、名空间、类名、或其他可疑修改
使用工具做条件编辑是否会报错
条件量级大概有多少
项目的资源类型是文本还是二进制
其他版本是否测试过

**Comment by Justin-sky** [comment]
这个报错没有显示报出来，我在debug状态下，展开data对象才看到的，工具代码直接拷贝到项目没有任何修改， asset serialization模式为Force Binary, 条件编辑没有报错，条件只有3个，开了global， global有5个
![image](https://user-images.githubusercontent.com/58215826/228120413-96309a38-9cc9-44b3-a45b-3b83df96e5a3.png)
![image](https://user-images.githubusercontent.com/58215826/228120443-78968776-b966-44e8-a905-e4bc35e3259d.png)
其它版本没试过

**Comment by Justin-sky** [comment]
我将项目中资源修改为text模式也是同样报错

**Comment by crossous** [comment]
我尝试了下，确实能复现，不过感觉是Rider的Bug
简单创建了一个自定义序列化的Dictionary，既继承ISerializationCallbackReceiver和Dictionary的可序列化类，在Rider的变量监控视窗中都会显示上述Exception，但实际上没有对使用造成影响
如果着的需要debug看变量值，可以展开用下面的RawView，也可以用Visual Studio，没有发生类似的问题
感谢你的反馈

**Comment by Justin-sky** [comment]
我发现这个问题主要是发现我配置剔除后，打包shader后没有剔除，我再测试下

**Comment by crossous** [comment]
目前我所知的有Standard这个Shader会因为未知原因无法被剔除。
可以尝试用一个材质或变体收集文件引用shader变体，然后单独将材质或变体收集文件打bundle进行断点测试
本来这个工具还支持剔除测试，但2021版本不让在 IPreprocessShaders 外使用 ShaderKeywordSet，所以只能靠老办法测试了，2021的剔除测试后续再考虑适配

**Comment by Justin-sky** [comment]
找到原因了，我在 “包含Keyword或集合” 这个条件选择了多个Keyword导致不能剔除

**Comment by crossous** [comment]
好的，这个issues先关闭了
